Repository DFE-Digital/refer-serious-misconduct, pull requests merged in 2023-01, with the labels that each got.

#355 Update ServicePrincipal names in sp-check workflow
  .github/workflows/check_sp.yml
Labels: devops

#303 Reduced resource requirements for ACI worker app
  terraform/app.tf
Labels: deploy, devops

#364 Add workflow dispatch trigger to deploy single env
  .github/workflows/build-and-deploy.yml
Labels: devops

#370 Add "About their role" public flow
  app/components/their_role_component.rb
  app/controllers/public_referrals/teacher_role/check_answers_controller.rb
  app/controllers/public_referrals/teacher_role/duties_controller.rb
  app/controllers/public_referrals/teacher_role/job_title_controller.rb
  app/controllers/public_referrals/teacher_role/organisation_address_controller.rb
  app/controllers/public_referrals/teacher_role/organisation_address_known_controller.rb
  app/controllers/referrals/teacher_role/check_answers_controller.rb
  app/controllers/referrals/teacher_role/duties_controller.rb
  app/controllers/referrals/teacher_role/job_title_controller.rb
  app/controllers/referrals/teacher_role/organisation_address_controller.rb
  app/controllers/referrals/teacher_role/organisation_address_known_controller.rb
  app/controllers/referrals/teacher_role/start_date_controller.rb
  app/forms/referral_form.rb
  app/views/referrals/teacher_role/check_answers/edit.html.erb
  app/views/referrals/teacher_role/duties/edit.html.erb
  app/views/referrals/teacher_role/job_title/edit.html.erb
  app/views/referrals/teacher_role/organisation_address/edit.html.erb
  app/views/referrals/teacher_role/organisation_address_known/edit.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/forms/referrals/teacher_role/organisation_address_form_spec.rb
  spec/system/public_referrals/user_adds_teacher_role_details_spec.rb
  spec/system/referrals/user_adds_teacher_role_details_spec.rb
Labels: deploy

#371 Fixed condition on non-prod deployment job
  .github/workflows/build-and-deploy.yml
Labels: deploy, devops

#411 1138 - Remove the autofocus on input fields
  app/views/staff/confirmations/new.html.erb
  app/views/staff/passwords/new.html.erb
  app/views/staff/sessions/new.html.erb
  app/views/staff/unlocks/new.html.erb
  app/views/users/sessions/new.html.erb
Labels: deploy

#427 Fix zip file download when using an external storage service
  app/lib/referral_zip_file.rb
Labels: deploy

#429 Upgrade to Ruby 3.2.0 and packages in .tool-versions
  .ruby-version
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: deploy
