Repository DFE-Digital/refer-serious-misconduct, pull requests merged in 2024-10, with the labels that each got.

#1199 Create review resource group in s189
  Makefile
  global_config/review.sh
Labels: devops

#1204 Add terraform config
  .gitignore
  Makefile
  config/environments/production.rb
  terraform/application/.terraform.lock.hcl
  terraform/application/application.tf
  terraform/application/cluster_data.tf
  terraform/application/config/review.tfvars.json
  terraform/application/config/review.yml
  terraform/application/config/review_Terrafile
  terraform/application/data.tf
  terraform/application/database.tf
  terraform/application/output.tf
  terraform/application/secrets.tf
  terraform/application/statuscake.tf
  terraform/application/storage.tf
  terraform/application/terraform.tf
  terraform/application/variables.tf
Labels: deploy, devops

#1211 AKS pipeline for RSM review app
  .github/actions/deploy-environment-aks/action.yml
  .github/pull_request_template.md
  .github/workflows/build-and-deploy.yml
  .github/workflows/delete-review-app.yml
  terraform/application/application.tf
  terraform/application/config/review.tfvars.json
  terraform/application/variables.tf
Labels: deploy-aks

#1220 Skip azure login in workflow
  Makefile
Labels: devops
